# Generated by Django 4.2.7 on 2025-11-04 14:03

from django.db import migrations, models
import text_analysis.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=text_analysis.models.uploaded_file_path)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('topics_json', models.JSONField(blank=True, null=True)),
                ('sentiment_distribution', models.JSONField(blank=True, null=True)),
                ('wordcloud_data', models.JSONField(blank=True, null=True)),
                ('extractive_summary', models.TextField(blank=True, null=True)),
                ('abstractive_summary', models.TextField(blank=True, null=True)),
                ('actionable_insights', models.JSONField(blank=True, null=True)),
                ('topic_chart_path', models.CharField(blank=True, max_length=500, null=True)),
                ('sentiment_chart_path', models.CharField(blank=True, max_length=500, null=True)),
                ('wordcloud_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_report', models.FileField(blank=True, null=True, upload_to=text_analysis.models.report_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
